/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.util.ArrayList;
import java.util.List;
import queries.Client;
import javax.swing.JOptionPane;

/**
 *
 * @author Rica Mae
 */
public class ClientSignUp extends javax.swing.JFrame {
    Client client = new Client();
    private String meterType = "";
    private int meterCount = 0;
    private int submeterCount = 0;
    private List<String> comMeterNames;
    private List<String> bulkSubmeterNames;
    private String primaryMeterName;
    
    public ClientSignUp() {
        initComponents();
       comMeterNames = new ArrayList<>(); 
       bulkSubmeterNames = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        contactnoField = new javax.swing.JTextField();
        passField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        selectLoc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        meternameField = new javax.swing.JTextField();
        meterSummaryLabel = new javax.swing.JLabel();
        totalMeterLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        addmeterButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        selectMeterType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        submeternameField = new javax.swing.JTextField();
        submetersSummary = new javax.swing.JLabel();
        totalSubmeters = new javax.swing.JLabel();
        addSubmeterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLIENT SIGN UP");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLIENT NAME");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTACT NUMBER");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS");

        selectLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barangay 11", "Barangay 12", "Bucana", "Wawa" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("METERS");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("METER NAME");

        meternameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meternameFieldActionPerformed(evt);
            }
        });

        meterSummaryLabel.setForeground(new java.awt.Color(255, 255, 255));
        meterSummaryLabel.setText("SUMMARY");

        totalMeterLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalMeterLabel.setText("TOTAL METERS:");

        cancelButton.setText("CANCEL");

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        addmeterButton.setText("ADD METER");
        addmeterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmeterButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CLIENT INFORMATION");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("METER TYPE");

        selectMeterType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Residential", "Commercial", "Bulk" }));
        selectMeterType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMeterTypeActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SUBMETER NAME");

        submetersSummary.setForeground(new java.awt.Color(255, 255, 255));
        submetersSummary.setText("SUMMARY");

        totalSubmeters.setForeground(new java.awt.Color(255, 255, 255));
        totalSubmeters.setText("TOTAL SUBMETERS:");

        addSubmeterButton.setText("ADD SUBMETER");
        addSubmeterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubmeterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(selectMeterType, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(376, 376, 376)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(meternameField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(submeternameField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(totalMeterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300)
                        .addComponent(totalSubmeters, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(meterSummaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(addmeterButton)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(submetersSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(addSubmeterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(selectLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactnoField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel12))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactnoField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectMeterType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meternameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submeternameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalMeterLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(totalSubmeters)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(meterSummaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(addmeterButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(submetersSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addSubmeterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectMeterTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMeterTypeActionPerformed
        String meterType = (String) selectMeterType.getSelectedItem();

        if (meterType.equals("Residential")) {
            meternameField.setEnabled(false);
            addmeterButton.setEnabled(false);
            submeternameField.setEnabled(false);
            addSubmeterButton.setEnabled(false);
        } else if (meterType.equals("Commercial")) {
            meternameField.setEnabled(true);
            addmeterButton.setEnabled(true);
            submeternameField.setEnabled(false);
            addSubmeterButton.setEnabled(false);
        } else if (meterType.equals("Bulk")) {
            meternameField.setEnabled(false);  // Primary meter
            addmeterButton.setEnabled(false);
            submeternameField.setEnabled(true);  // Submeters
            addSubmeterButton.setEnabled(true);
        }
    }//GEN-LAST:event_selectMeterTypeActionPerformed

    private void addmeterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmeterButtonActionPerformed
        String meterType = (String) selectMeterType.getSelectedItem();
        String meterName = meternameField.getText().trim();

        if (meterType.equals("Commercial")) {
            if (!meterName.isEmpty()) {
                comMeterNames.add(meterName);
                meterCount++;
                meternameField.setText("");
                updateMeterSummary();
            } else {
                JOptionPane.showMessageDialog(this, "Meter name cannot be empty!");
            }
        } else if (meterType.equals("Bulk")) {
            if (primaryMeterName == null) {
                primaryMeterName = meterName.isEmpty() ? "Main Meter" : meterName;
                meternameField.setText("");
                JOptionPane.showMessageDialog(this, "Primary meter set as: " + primaryMeterName);
            } else {
                if (!meterName.isEmpty()) {
                    bulkSubmeterNames.add(meterName);
                    meterCount++;
                    meternameField.setText("");
                    updateMeterSummary();
                } else {
                    JOptionPane.showMessageDialog(this, "Submeter name cannot be empty!");
                }
            }
        }

    }//GEN-LAST:event_addmeterButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        handleSubmit();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void meternameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meternameFieldActionPerformed

    }//GEN-LAST:event_meternameFieldActionPerformed

    private void addSubmeterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubmeterButtonActionPerformed
        String submeterName = submeternameField.getText();

        if (!submeterName.isEmpty()) {
            bulkSubmeterNames.add(submeterName); // Save to the list of submeters
            submeterCount++;
            submeternameField.setText("");
            updateSubmeterSummary();
        } else {
            JOptionPane.showMessageDialog(this, "Submeter name cannot be empty!");
        }
    }//GEN-LAST:event_addSubmeterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    private void updateMeterSummary() {
        totalMeterLabel.setText("Total Meters: " + meterCount);

        StringBuilder summary = new StringBuilder("<html>Meter Summary:<br>");
        for (String meter : comMeterNames) {
            summary.append("- ").append(meter).append("<br>");
        }
        if (primaryMeterName != null) {
            summary.append("- Primary Meter: ").append(primaryMeterName).append("<br>");
        }
        for (String submeter : bulkSubmeterNames) {
            summary.append("- Submeter: ").append(submeter).append("<br>");
        }
        summary.append("</html>");

        meterSummaryLabel.setText(summary.toString());
    }
   
    private void updateSubmeterSummary() {
        StringBuilder summary = new StringBuilder("<html>Submeter Summary:<br>");
        for (String submeterName : bulkSubmeterNames) {
            summary.append("- ").append(submeterName).append("<br>");
        }
        summary.append("</html>");

        submetersSummary.setText(summary.toString()); // Update the JLabel for submeters
    }


    private void handleSubmit() {
        String clientName = nameField.getText().trim();
        String contactNumber = contactnoField.getText().trim();
        String password = passField.getText().trim();
        int addressID = selectLoc.getSelectedIndex() + 1;
        String meterType = (String) selectMeterType.getSelectedItem();

        if (clientName.isEmpty() || contactNumber.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Integer primaryMeterID = null; // Initialize primaryMeterID

        if (meterType.equals("Bulk") && (primaryMeterName == null || primaryMeterName.isEmpty())) {
            primaryMeterName = "Main Meter"; // Set default name if missing
        }

        // Insert the client first and retrieve clientID
        int clientID = client.insertClient(clientName, contactNumber, password, addressID, meterType);

        if (meterType.equals("Bulk")) {
            // Insert the primary meter and retrieve its ID
            primaryMeterID = client.insertMeter(clientID, primaryMeterName, "Primary");
            if (primaryMeterID == null) {
                JOptionPane.showMessageDialog(this, "Failed to insert primary meter.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Stop further processing
            }

            // Ensure at least one submeter is provided
            if (bulkSubmeterNames.isEmpty()) {
                JOptionPane.showMessageDialog(this, "At least one submeter name is required for Bulk meters.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Stop further processing
            }

            // Insert submeters using the retrieved primaryMeterID
            for (String submeterName : bulkSubmeterNames) {
                client.insertSubmeter(primaryMeterID, submeterName);
            }
        }


        if (meterType.equals("Residential")) {
            client.insertMeter(clientID, "Default Meter", "Residential");
        } else if (meterType.equals("Commercial")) {
            if (comMeterNames.isEmpty()) {
                JOptionPane.showMessageDialog(this, "At least one meter name is required for Commercial meters.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            for (String meterName : comMeterNames) {
                client.insertMeter(clientID, meterName, "Commercial");
            }
        }

        JOptionPane.showMessageDialog(
            this,
            "Client added successfully!\nGenerated Client ID: " + clientID,
            "Success",
            JOptionPane.INFORMATION_MESSAGE
        );

        clearForm();
    }

    private void clearForm() {
        nameField.setText("");
        contactnoField.setText("");
        passField.setText("");
        selectLoc.setSelectedIndex(0);
        selectMeterType.setSelectedIndex(0);
        meternameField.setText("");
        comMeterNames.clear();
        bulkSubmeterNames.clear();
        meterCount = 0;
        primaryMeterName = null;

        updateMeterSummary();
        updateSubmeterSummary();
    }





    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubmeterButton;
    private javax.swing.JButton addmeterButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField contactnoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel meterSummaryLabel;
    private javax.swing.JTextField meternameField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField passField;
    private javax.swing.JComboBox<String> selectLoc;
    private javax.swing.JComboBox<String> selectMeterType;
    private javax.swing.JTextField submeternameField;
    private javax.swing.JLabel submetersSummary;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel totalMeterLabel;
    private javax.swing.JLabel totalSubmeters;
    // End of variables declaration//GEN-END:variables
}
