
package wbs_2103.src.gui;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import wbs_2103.src.queries.Collector;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import queries.Client;
import static queries.SharedData.clientID;

/**
 *
 * @author Nhel Hernadez
 */
public class CollectorUI extends javax.swing.JFrame {
     Collector collector = new Collector();
     private DefaultTableModel tableModel;
     private double billAmount;
     private double currentReading;
     private double previousReading;
     private double penaltyCharge;
     private double leakCharge;
     private double charges;
     private LocalDate latestpaymentdate;

    /**
     * Creates new form CollectorUI
     */
    public CollectorUI() {
        initComponents();
        //collector = new Collector();
       populateClientReadTable();

    }
    
    private void populateClientReadTable() {
    // Clear existing rows in the table
    DefaultTableModel model = (DefaultTableModel) ClientRead.getModel();
    model.setRowCount(0);

    List<String[]> clientMeterData = collector.fetchClientMeterData();

    for (String[] row : clientMeterData) {
        model.addRow(row);
    }

    // Refresh the table UI
    ClientRead.repaint();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Collect = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClientRead = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        prevRead = new javax.swing.JLabel();
        currentRead = new javax.swing.JLabel();
        billAmountLabel = new javax.swing.JLabel();
        meterIDField = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        send = new javax.swing.JButton();
        hasLeak = new javax.swing.JCheckBox();
        status = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        clientid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        udStatus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Collect.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CollectStateChanged(evt);
            }
        });

        ClientRead.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ClientID", "Client Name", "MeterName", "MeterID", "MeterType", "Address", "Previous Reading", "Current Reading", "Last Payment"
            }
        ));
        jScrollPane2.setViewportView(ClientRead);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        Collect.addTab("Overview of Clients", jPanel4);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("MeterID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 65, 98, 31));

        prevRead.setText("Previos Reading");
        jPanel2.add(prevRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 206, 174, 40));

        currentRead.setText("Current Reading");
        jPanel2.add(currentRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 169, 155, 31));

        billAmountLabel.setText("Bill Amount");
        jPanel2.add(billAmountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 246, 155, 28));
        jPanel2.add(meterIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 65, 149, 30));

        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        jPanel2.add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 109, 98, 35));

        send.setText("SEND TO CLIENT");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel2.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 304, 150, 32));

        hasLeak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hasLeak.setText("has leakage?");
        jPanel2.add(hasLeak, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 108, 149, 35));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "INACTIVE" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel2.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 108, 158, 37));

        jLabel4.setText("ClientID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 60, 98, 25));
        jPanel2.add(clientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 57, 164, 30));

        jLabel3.setText("UPDATE CLIENT STATUS");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 118, 151, -1));

        udStatus.setText("UPDATE STATUS");
        udStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udStatusActionPerformed(evt);
            }
        });
        jPanel2.add(udStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 133, 33));

        Collect.addTab("Reading Area", jPanel2);

        jPanel3.add(Collect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wbs_2103/src/icons/website design (1) (1).png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 960, 460));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, -1, -1));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Collector Interface");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 337, 75));

        logoutButton.setText("LOG OUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 101, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wbs_2103/src/icons/website design (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        CollectorSignIn collector = new CollectorSignIn();
        collector.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void CollectStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CollectStateChanged
        populateClientReadTable();
    }//GEN-LAST:event_CollectStateChanged

    private void udStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udStatusActionPerformed
        String selectedStatus = (String) status.getSelectedItem();
        Client client = new Client();
        int clientID = Integer.parseInt(clientid.getText());
        client.updateClientStatus(clientID, selectedStatus);
    }//GEN-LAST:event_udStatusActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed

    }//GEN-LAST:event_statusActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        String meterId = meterIDField.getText();
        double totalBill = billAmount + charges;  // Ensure totalBill includes charges
        double meterUsed = currentReading - previousReading;  // Calculate meterUsed

        if (currentReading == previousReading){
            JOptionPane.showMessageDialog(null,
                "No bill to send",
                "Reminder",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int clientId = collector.fetchClientIDByMeterID(meterId);

        if (clientId != -1) {
            if (collector.saveBillToDatabase(clientId, meterId, totalBill, leakCharge, penaltyCharge, meterUsed)) {
                JOptionPane.showMessageDialog(null,
                    "Bill sent to client successfully.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                collector.updateMeterReading(meterId, currentReading);
            } else {
                JOptionPane.showMessageDialog(null,
                    "Error sending the bill.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null,
                "No client found for the provided meter ID.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sendActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        calculateBillButton();
    }//GEN-LAST:event_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    
private void calculateBillButton() {
    String meterId = meterIDField.getText();

    // Fetch meter readings
    Map<String, String> meterReadings = collector.fetchMeterReadings(meterId);

    if (meterReadings.isEmpty()) {
        JOptionPane.showMessageDialog(null, 
            "No meter readings found for the provided meter ID.", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    previousReading = Double.parseDouble(meterReadings.get("previousReading"));
    currentReading = Double.parseDouble(meterReadings.get("currentReading"));

    double cubicMetersUsed = currentReading - previousReading;  // Calculate meterUsed

    billAmount = cubicMetersUsed * 15;
    String billAmountStr = String.format("%.2f", billAmount);

    prevRead.setText("Previous Reading: " + String.valueOf(previousReading)); // Set previous reading
    currentRead.setText("Current Reading: " + String.valueOf(currentReading));   // Set current reading
    billAmountLabel.setText("Bill Amount: " + billAmountStr);

    // Fetch client ID
    int clientId = collector.fetchClientIDByMeterID(meterId);

    // Reset charges
    penaltyCharge = 0;
    leakCharge = 0;

    // Fetch last payment date
    LocalDate lastPaymentDate = collector.fetchLastPaymentDate(clientId);

    // Determine penalty charge
    if (lastPaymentDate != null) {
        LocalDate today = LocalDate.now();
        long overdueDays = ChronoUnit.DAYS.between(lastPaymentDate, today);

        if (overdueDays > 30) {  // Apply penalty if overdue by more than 30 days
            penaltyCharge = 50.0; // Set penalty charge amount
        }
    }

    // Determine leak charges based on user selection
    boolean leak = hasLeak.isSelected();
    if (leak) {
        leakCharge = 30.0; 
    }

    // Calculate total charges
    charges = penaltyCharge + leakCharge;

    // Add charges to the billAmount
    double totalBill = billAmount + charges;  // Update the total bill with charges
    String totalBillStr = String.format("%.2f", totalBill);

    // Show breakdown of charges
    StringBuilder breakdown = new StringBuilder();
    breakdown.append("Charges Breakdown:\n");
    breakdown.append("Penalty Charge: ").append(String.format("%.2f", penaltyCharge)).append(" pesos\n");
    breakdown.append("Leak Charge: ").append(String.format("%.2f", leakCharge)).append(" pesos\n\n");
    breakdown.append("Total Charges: ").append(String.format("%.2f", charges)).append(" pesos\n");
    breakdown.append("Total Bill Amount: ").append(totalBillStr);

    if (lastPaymentDate != null) {
        breakdown.append("\nLast Payment Date: ").append(lastPaymentDate);
    } else {
        breakdown.append("\nLast Payment Date: No record found");
    }

    JOptionPane.showMessageDialog(null, breakdown.toString(), "Charges Breakdown", JOptionPane.INFORMATION_MESSAGE);
}






    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollectorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollectorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollectorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollectorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollectorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientRead;
    private javax.swing.JTabbedPane Collect;
    private javax.swing.JLabel billAmountLabel;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField clientid;
    private javax.swing.JLabel currentRead;
    private javax.swing.JCheckBox hasLeak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField meterIDField;
    private javax.swing.JLabel prevRead;
    private javax.swing.JButton send;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JButton udStatus;
    // End of variables declaration//GEN-END:variables


}
